### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by hawk7476** [iQuickGaming/QuickRAT-Host#1]
when we compile it shows errors.Have you successfully compiled?Please can you tell me it's features

**Comment by iQuickDev** [comment]
the project is not complete, it is under development and it won't compile

**Comment by hawk7476** [comment]
when it can be available?when it will complete ?please ..thamks for your effort

**Comment by iQuickDev** [comment]
there's not any ETA, i'll just develop it when i have time
